const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Plugins.Keyboard,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Behaviors.Platform.Cnds.IsJumping
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Tomate: 0},
	{Teclado: 0},
	{Platform: 0},
	{esqueleto: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{morto: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{fox: 0},
	{fundo: 0},
	{Solid: 0},
	{Sprite: 0},
	{TiledBackground: 0},
	{Sprite2: 0},
	{TiledBackground2: 0},
	{TiledBackground3: 0},
	{TiledBackground4: 0},
	{Cogu: 0},
	{Sprite4: 0},
	{colision: 0},
	{morreu: 0}
];

self.InstanceType = {
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Tomate: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	esqueleto: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	fox: class extends self.ISpriteInstance {},
	fundo: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Cogu: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	colision: class extends self.ISpriteInstance {}
}